[project]
name = "invoice-api"
version = "0.1.0"
description = "Invoice API"
readme = "README.md"
authors = [
    { name = "Rubén Prikhodtchenko Shumilo", email = "rubenps2409@gmail.com" }
]
requires-python = ">=3.10"
dependencies = []

[project.scripts]
invoice-api = "invoice_api:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"

[tool.fastapi]
entrypoint = "src.invoice_api.main:app"