[project]
name = "invoice-api"
version = "0.1.0"
description = "Invoice API"
readme = "README.md"
authors = [
    { name = "Rubén Prikhodtchenko Shumilo", email = "rubenps2409@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.143.0",
    "pydantic-settings>=2.15.0",
]

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"

[tool.fastapi]
entrypoint = "invoice_api.main:app"
